{
 "title": "JupyterHub - User pods / cluster state",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "default" }
  ]
 },
 "panels": [
  {
   "title": "User pod's phase",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{pod=~\"jupyter-.*\", phase=~\"Failed|Succeeded|Unknown\", kubernetes_namespace=\"$namespace\"}) by (phase)"
    },
    {
     "expr": "sum(kube_pod_status_phase{pod=~\"jupyter-.*\", phase=~\"Pending\", kubernetes_namespace=\"$namespace\"}) by (phase)"
    },
    {
     "expr": "sum(kube_pod_status_phase{pod=~\"jupyter-.*\", phase=~\"Running\", kubernetes_namespace=\"$namespace\"}) by (phase)"
    }
   ]
  },
  {
   "title": "JupyterHub response latency",
   "type": "heatmap",
   "description": "The only request typically taking longer than 1s is the culler's delete requests and the request regarding progress.\n\n- 204 DELETE /hub/api/users/user1/server (cull-idle@127.0.0.1) 7828.61ms\n- 200 GET /hub/api/users/pmetzak/server/progress (user2@10.60.32.8) 33981.03ms\n\nThe requests between 500-1000ms seem to be authentication related.\n\n- 200 GET /hub/api/authorizations/token/[secret] (user3@10.64.6.212) 417.08ms\n- 302 GET /hub/oauth_callback?code=[secret]&state=[secret] -> /user/user4/ (@10.60.32.7) 777.27ms",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(request_duration_seconds_bucket{app='jupyterhub', kubernetes_namespace=\"$namespace\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Server Spawn Times",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(server_spawn_duration_seconds_bucket{kubernetes_namespace=\"$namespace\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "JupyterHub Response Codes",
   "type": "graph",
   "description": "503 errors are typically JupyterHub servers that have been culled. When that happens, JupyterHub's configurable proxy will remove the route from /user/<servername> and such requests will be redirected to /hub/user/<servername> instead. This is when a 503 response is sent back.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(request_duration_seconds_count{app=\"jupyterhub\", component=\"hub\", kubernetes_namespace=\"$namespace\"}[5m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "User pod terminated reason",
   "type": "graph",
   "description": "I think pods enter the completed state when the culler culls them.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated_reason{pod=~\"jupyter-.*\", kubernetes_namespace=\"$namespace\"}) by (reason)"
    }
   ]
  },
  {
   "title": "Node Count",
   "type": "graph",
   "description": "Total Number of Nodes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(kube_node_info)" }
   ]
  },
  {
   "title": "Kubelet's pod startup latency",
   "type": "heatmap",
   "description": "Note these are all pods on the user nodes, not only the user-pods.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "kubelet_pod_start_latency_microseconds{hub_jupyter_org_node_purpose=\"user\"}"
    }
   ]
  },
  {
   "title": "Cluster Allocations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes and on (pod) (kube_pod_container_status_ready)) / sum(kube_node_status_allocatable_memory_bytes) ",
     "legendFormat": "memory"
    },
    {
     "expr": "count(kube_pod_info) / sum(kube_node_status_allocatable_pods)   ",
     "legendFormat": "pods"
    }
   ]
  }
 ]
}